#!/usr/bin/python3
'''
A script that starts a Flask web application
'''

from flask import Flask

app = Flask(__name__)

@app.route('/', stict_slashes=False)
def homepage():
    return f"Hello HBNB!"


if __name__ == '__main__':
    app.run()